title: 'Mad Props Photo Booth Co. '
baseurl: /
permalink: '/:title/'
palette: orange
header:
  has_nav: true
  logo_img: /images/orange_logo_long.png
  menu:
    actions:
      - label: 'Contact us '
        url: /contactus
  title: 'Mad Props Photo Booth Co. '
footer:
  content: '&copy; Mad Props Photo Booth Co. All rights reserved.'
  has_nav: true
  has_social: true
  has_subscribe: true
  links:
    - new_window: true
      text: 'Email Us '
      url: >-
        mailto:madpropsphotobooth@gmail.com?subject=Interested In Booking An
        Event 
  logo_img: /images/orange_logo_full.png
  nav_title: Company
  social_title: Community
  subscribe_content: 'Have us at your next event. Sign up now. '
  subscribe_title: 'Hire Us '
  tagline: 'Mad Props Photobooth Co. '
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
